from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


def generate_pdf(analysis):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        fontSize=20,
        spaceAfter=14,
        alignment=1  # center
    )

    section_style = ParagraphStyle(
        "SectionStyle",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#0d6efd"),
        spaceAfter=8
    )

    normal = styles["BodyText"]

    story = []

    # ================= HEADER =================
    story.append(Paragraph("AI Banking Complaint Resolution Report", title_style))
    story.append(Spacer(1, 10))

    # ================= BASIC INFO TABLE =================
    story.append(Paragraph("Complaint Overview", section_style))

    overview_data = [
        ["Complaint", analysis.complaint_text],
        ["Category", analysis.category],
        ["Urgency", analysis.urgency],
        ["Priority", analysis.priority],
        ["Eligibility", analysis.eligibility],
    ]

    table = Table(overview_data, colWidths=[120, 350])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.whitesmoke, colors.lightgrey]),
    ]))

    story.append(table)
    story.append(Spacer(1, 15))

    # ================= RESOLUTION STEPS =================
    story.append(Paragraph("Resolution Steps", section_style))

    for i, step in enumerate(analysis.resolution_steps, 1):
        story.append(Paragraph(f"{i}. {step}", normal))
        story.append(Spacer(1, 4))

    story.append(Spacer(1, 10))

    # ================= TIMELINE =================
    story.append(Paragraph("Expected Timeline", section_style))

    for item in analysis.timeline:
        story.append(Paragraph(f"• {item}", normal))

    story.append(Spacer(1, 10))

    # ================= INSIGHTS =================
    story.append(Paragraph("AI Insights", section_style))

    insights = [
        f"Success Probability: {analysis.success_probability}",
        f"Estimated Resolution Time: {analysis.estimated_time}",
    ]

    for ins in insights:
        story.append(Paragraph(ins, normal))

    story.append(Spacer(1, 10))

    # ================= PREVENTIVE ADVICE =================
    story.append(Paragraph("Preventive Advice", section_style))

    for advice in analysis.preventive_advice:
        story.append(Paragraph(f"✔ {advice}", normal))

    story.append(Spacer(1, 10))

    # ================= CLASSIFIER INFO =================
    story.append(Paragraph("Model Confidence", section_style))

    story.append(Paragraph(
        f"Confidence Score: {analysis.confidence_score:.4f}",
        normal
    ))

    story.append(Spacer(1, 20))

    # ================= FOOTER =================
    story.append(Paragraph(
        "Generated by AI Banking Complaint Resolution System",
        styles["Italic"]
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer